#!/usr/bin/env bash

sudo apt purge git 
sudo apt purge libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libreadline-dev libssl-dev zlib1g-dev libsnappy-dev libsqlite3-dev 
sudo apt purge sqlite3 
sudo apt purge postgresql 
sudo apt purge libpq-dev 
sudo apt purge redis 
sudo apt purge libtool advancecomp gifsicle jpegoptim libjpeg-progs optipng pngcrush pngquant jhead 
sudo apt purge nodejs npm 
sudo rm /usr/local/bin/redis-*
sudo rm /etc/redis/redis.conf
sudo rm -r /etc/redis/
sudo rm -r /var/lib/redis/
sudo rm /etc/init.d/redis_*
sudo rm /var/run/redis_*
sudo rm -rf /usr/local/bin/npm 
sudo rm -rf /usr/local/share/man/man1/node* 
sudo rm -rf /usr/local/lib/dtrace/node.d
rm -rf ~/.npm
rm -rf ~/.node-gyp
sudo rm -rf /opt/local/bin/node
sudo rm -rf /opt/local/include/node
sudo rm -rf /opt/local/lib/node_modules
sudo rm -rf /usr/local/lib/node*
sudo rm -rf /usr/local/include/node*
sudo rm -rf /usr/local/bin/node*
