#!/usr/bin/env bash

sudo apt purge -y git 
sudo apt purge -y libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libreadline-dev libssl-dev zlib1g-dev libsnappy-dev libsqlite3-dev 
sudo apt purge -y sqlite3 
sudo apt purge -y postgresql 
sudo apt purge -y libpq-dev 
sudo apt purge -y redis redis-*
sudo apt purge -y libtool advancecomp gifsicle jpegoptim libjpeg-progs optipng pngcrush pngquant jhead 
sudo apt purge -y nodejs npm 
sudo apt purge -y git-man gnupg-l10n gpg-wks-server liberror-perl libjbig-dev libjpeg-turbo-progs libltdl-dev liblzma-dev libpng-tools libtiffxx5
sudo apt -y autoremove
sudo rm /usr/local/bin/redis-*
sudo rm /etc/redis/redis.conf
sudo rm -rf /etc/redis/
sudo rm -rf /var/lib/redis/
sudo rm /etc/init.d/redis_*
sudo rm /var/run/redis_*
sudo rm -rf /usr/local/bin/npm 
sudo rm -rf /usr/local/share/man/man1/node* 
sudo rm -rf /usr/local/lib/dtrace/node.d
rm -rf ~/.npm
rm -rf ~/.node-gyp
sudo rm -rf /opt/local/bin/node
sudo rm -rf /opt/local/include/node
sudo rm -rf /opt/local/lib/node_modules
sudo rm -rf /usr/local/lib/node*
sudo rm -rf /usr/local/include/node*
sudo rm -rf /usr/local/bin/node*
